<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>New Product Request</title>
    <style>
        body { font-family: Arial, sans-serif; background-color: #f4f6f8; margin: 0; padding: 20px; color: #333; }
        .container { max-width: 650px; background: #ffffff; border-radius: 8px; overflow: hidden; padding: 25px; margin: 0 auto; box-shadow: 0 4px 10px rgba(0,0,0,0.05); }
        .header { background: #0284c7; color: #ffffff; padding: 20px; text-align: center; border-radius: 6px; }
        .header h2 { margin: 0; font-size: 22px; }
        .section { margin-top: 20px; }
        .section-title { font-size: 16px; font-weight: bold; color: #0369a1; border-bottom: 2px solid #e0f2fe; padding-bottom: 5px; margin-bottom: 12px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { padding: 10px 12px; border: 1px solid #e5e7eb; text-align: left; font-size: 14px; }
        th { background-color: #f8fafc; color: #475569; }
        .total-row { font-weight: bold; background-color: #f0f9ff; }
        .footer { text-align: center; font-size: 12px; color: #94a3b8; margin-top: 25px; border-top: 1px solid #e2e8f0; padding-top: 15px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h2>Petchemparts - New Product Quote Request</h2>
            <p style="margin: 5px 0 0 0;">Request Number: <strong>#{{ $productRequest->request_number }}</strong></p>
        </div>

        <div class="section">
            <div class="section-title">Customer Information</div>
            <p><strong>Name:</strong> {{ $productRequest->customer_name }}</p>
            <p><strong>Email:</strong> {{ $productRequest->customer_email }}</p>
            <p><strong>Phone:</strong> {{ $productRequest->customer_phone }}</p>
            @if($productRequest->notes)
                <p><strong>Message / Notes:</strong> {{ $productRequest->notes }}</p>
            @endif
        </div>

        <div class="section">
            <div class="section-title">Requested Products</div>
            <table>
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Product Name</th>
                        <th>Part Number</th>
                        <th>Est. Price</th>
                        <th>Qty</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    @php $grandTotal = 0; @endphp
                    @foreach($productRequest->items as $index => $item)
                        @php 
                            $subtotal = $item->price * $item->quantity; 
                            $grandTotal += $subtotal;
                        @endphp
                        <tr>
                            <td>{{ $index + 1 }}</td>
                            <td><strong>{{ $item->product_name }}</strong></td>
                            <td>{{ $item->part_number ?? 'N/A' }}</td>
                            <td>£{{ number_format($item->price, 2) }}</td>
                            <td>{{ $item->quantity }}</td>
                            <td>£{{ number_format($subtotal, 2) }}</td>
                        </tr>
                    @endforeach
                    <tr class="total-row">
                        <td colspan="5" style="text-align: right;">Total Estimated Value:</td>
                        <td>£{{ number_format($grandTotal, 2) }}</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="footer">
            <p>This email was automatically generated by Petchemparts Petchemparts Website Request System.</p>
        </div>
    </div>
</body>
</html>
